/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Collapsible`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/Colors`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useColorScheme`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/CustomButton`; params?: Router.UnknownInputParams; } | { pathname: `/../src/icons/BirthdateScreenIllustrationIcon`; params?: Router.UnknownInputParams; } | { pathname: `/../src/utils/colors`; params?: Router.UnknownInputParams; } | { pathname: `/../src/store/index`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/Collapsible`; params?: Router.UnknownOutputParams; } | { pathname: `/../constants/Colors`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/useColorScheme`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/CustomButton`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/icons/BirthdateScreenIllustrationIcon`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/utils/colors`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/store/index`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `${'/(tabs)'}/index${`?${string}` | `#${string}` | ''}` | `/index${`?${string}` | `#${string}` | ''}` | `/../components/Collapsible${`?${string}` | `#${string}` | ''}` | `/../constants/Colors${`?${string}` | `#${string}` | ''}` | `/../hooks/useColorScheme${`?${string}` | `#${string}` | ''}` | `/../src/components/CustomButton${`?${string}` | `#${string}` | ''}` | `/../src/icons/BirthdateScreenIllustrationIcon${`?${string}` | `#${string}` | ''}` | `/../src/utils/colors${`?${string}` | `#${string}` | ''}` | `/../src/store/index${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Collapsible`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/Colors`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useColorScheme`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/CustomButton`; params?: Router.UnknownInputParams; } | { pathname: `/../src/icons/BirthdateScreenIllustrationIcon`; params?: Router.UnknownInputParams; } | { pathname: `/../src/utils/colors`; params?: Router.UnknownInputParams; } | { pathname: `/../src/store/index`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
